# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: gardenlogin-system # namespace should not start with garden- to prevent name clashes with project namespaces

namePrefix: gardenlogin- # must match with namePrefix defined in ../../default/kustomization.yaml

commonLabels:
  component: gardenlogin-manager

resources:
- manager
- ../../../rbac-rt
