# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: eu.gcr.io/gardener-project/development/images/gardenlogin-controller-manager
  newTag: v0.1.0-dev-16032a2d70e117626bcaead5a9808185fdb47cbf
