apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: applicationClusterEndpoint
    required: false
    type: data
    schema:
      type: string
  - name: applicationClusterTarget
    required: false
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: runtimeClusterTarget
    required: false
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: singleClusterTarget
    required: false
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: multiClusterDeploymentScenario
    required: true
    type: data
    schema:
      type: boolean

  - name: namePrefix
    required: true
    type: data
    schema:
      type: string

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: managerResources
    type: data
    required: false
    schema:
      $ref: "local://resourceRequirements"

  - name: kubeRbacProxyResources
    type: data
    required: false
    schema:
      $ref: "local://resourceRequirements"

  - name: managerConfig
    type: data
    required: false
    schema:
      type: object
      properties:
        kind:
          type: string
        apiVersion:
          type: string
        controllers:
          type: object
          properties:
            shoot:
              type: object
              properties:
                maxConcurrentReconciles:
                  type: integer
                maxConcurrentReconcilesPerNamespace:
                  type: integer
                quotaExceededRetryDelay:
                  type: number # int64
                  minimum: -9223372036854775808
                  maximum: 9223372036854775807
        webhooks:
          type: object
          properties:
            configMapValidation:
              type: object
              properties:
                maxObjectSize:
                  type: integer

localTypes:
  resourceRequirements:
    type: object
    properties:
      limits:
        $ref: "local://resourceList"
      requests:
        $ref: "local://resourceList"
  resourceList:
    type: object
    properties:
      cpu:
        type: string
      memory:
        type: string

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
  - file: /gardenlogin-deploy-execution.yaml
    name: manifests
    type: GoTemplate
