#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."

echo "> building component gardenlogin-controller-manager"

CA_PATH="$(mktemp -d)"
mv "$COMPONENT_DESCRIPTOR_PATH" "$CA_PATH/component-descriptor.yaml"

echo "CA_PATH ${CA_PATH}"

component-cli component-archive "${CA_PATH}" "${CTF_PATH}" \
    -r  "$SOURCE_PATH"/.landscaper/resources.yaml \
    VERSION="${EFFECTIVE_VERSION}"
