# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: garden-login-controller-secret-kubeconfig
            mountPath: /etc/gardener-garden-login-controller/secrets/kubeconfig
            readOnly: true
        env:
          - name: KUBECONFIG
            value: /etc/gardener-garden-login-controller/secrets/kubeconfig/kubeconfig
      volumes:
        - name: garden-login-controller-secret-kubeconfig
          secret:
            secretName: kubeconfig
