# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-garden-login
      url: null
    name: mutating-create-update-garden-login.gardener.cloud
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-garden-login
      url: null
    name: validating-create-update-garden-login.gardener.cloud
