// Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
// SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package gardenlogin

import (
	"context"
	"fmt"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	kErros "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Delete runs the delete operation. It clears all resources that were previously generated by the deploy container.
func (o *operation) Delete(ctx context.Context) error {
	err := o.deleteRuntimeResources(ctx)
	if err != nil {
		return fmt.Errorf("failed to delete runtime resources %w", err)
	}

	err = o.deleteApplicationResources(ctx)
	if err != nil {
		return fmt.Errorf("failed to delete application resources %w", err)
	}

	return nil
}

// deleteRuntimeResources deletes the runtime cluster specific resources of the gardenlogin-controller-manager if not already deleted
func (o *operation) deleteRuntimeResources(ctx context.Context) error {
	rtClient := o.runtimeCluster().client

	ns := &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: o.imports.Namespace}}
	if err := rtClient.Delete(ctx, ns); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	crb := &rbacv1.ClusterRoleBinding{ObjectMeta: metav1.ObjectMeta{Name: fmt.Sprintf("%sproxy-rolebinding", o.imports.NamePrefix)}}
	if err := rtClient.Delete(ctx, crb); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	cr := &rbacv1.ClusterRole{ObjectMeta: metav1.ObjectMeta{Name: fmt.Sprintf("%sproxy-role", o.imports.NamePrefix)}}
	if err := rtClient.Delete(ctx, cr); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	return nil
}

// deleteApplicationResources deletes the application cluster specific resources of the gardenlogin-controller-manager if not already deleted
func (o *operation) deleteApplicationResources(ctx context.Context) error {
	appClient := o.applicationCluster().client

	ns := &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: o.imports.Namespace}}
	if err := appClient.Delete(ctx, ns); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	crb := &rbacv1.ClusterRoleBinding{ObjectMeta: metav1.ObjectMeta{Name: fmt.Sprintf("%smanager-rolebinding", o.imports.NamePrefix)}}
	if err := appClient.Delete(ctx, crb); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	cr := &rbacv1.ClusterRole{ObjectMeta: metav1.ObjectMeta{Name: fmt.Sprintf("%smanager-role", o.imports.NamePrefix)}}
	if err := appClient.Delete(ctx, cr); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	vwc := &admissionregistrationv1.ValidatingWebhookConfiguration{ObjectMeta: metav1.ObjectMeta{Name: fmt.Sprintf("%svalidating-webhook-configuration", o.imports.NamePrefix)}}
	if err := appClient.Delete(ctx, vwc); err != nil && !kErros.IsNotFound(err) {
		return err
	}

	return nil
}
