# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      component: gardenlogin-manager

namespace: gardenlogin-system # namespace should not start with garden- to prevent name clashes with project namespaces
namePrefix: gardenlogin- # must match with namePrefix defined in ../../default/kustomization.yaml

resources:
- ../../default
- ../../rbac
- ../../rbac-rt
- ../../secret
- webhook-admission
- manager

replacements:
- source:
    kind: Secret
    version: v1
    name: webhook-server-cert
    fieldPath: data.[tls.crt]
  targets:
  - select:
      name: validating-webhook-configuration
      kind: ValidatingWebhookConfiguration
    fieldPaths:
    - webhooks.[name=validating-create-update-gardenlogin.gardener.cloud].clientConfig.caBundle
    options:
      create: true
