# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: gardenlogin-system # namespace should not start with garden- to prevent name clashes with project namespaces

namePrefix: gardenlogin- # must match with namePrefix defined in ../../default/kustomization.yaml

commonLabels:
  component: gardenlogin-manager

resources:
- ../../default
- ../../rbac
- ../../rbac-rt
- ../../secret
- webhook-admission
- manager

vars:
  - name: TLSCERT # somehow this var cannot be defined in the config/webhook-admission/kustomization.yaml
    objref:
      kind: Secret
      version: v1
      name: webhook-server-cert
    fieldref:
      fieldpath: data[tls.crt]
